stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
      - saas-windows-medium-amd64
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . 
    - echo "Compile complete."
