name: Publish Doxygen Docs (versioned and latest)

on:
  push:
    branches: [master, main]
    tags:
      - '*'       # Any tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            export PROJECT_NUMBER="${GITHUB_REF##*/}"
          else
            export PROJECT_NUMBER="latest"
          fi
          sed "s|@PROJECT_NUMBER@|$PROJECT_NUMBER|g" Doxyfile.in > Doxyfile
          doxygen Doxyfile
  
      # Determine if this is a tag or branch build
      - name: Set destination_dir
        id: destdir
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "dir=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          else
            echo "dir=latest" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/api
          destination_dir: ${{ steps.destdir.outputs.dir }}
          keep_files: true
