name: Static Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  

jobs:
  static-analysis:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (clang-tidy & cppcheck)
        run: |
          choco install -y cppcheck

      - name: Install Python dependencies
        run: pip install lxml jinja2 pygments

      - name: Add LLVM and cppcheck to PATH
        run: |
          # echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Cppcheck" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      # - name: Run clang-tidy
      #   run: clang-tidy src/*.c -p build || exit 0

      - name: Run cppcheck
        run: |
          $cmds = Get-Content build/compile_commands.json -Raw | ConvertFrom-Json
          $includes = @()
          foreach ($cmd in $cmds) {
              if ($cmd.command) {
                  $inc = ($cmd.command -split " ") | Where-Object { $_ -like "-I*" }
                  $includes += $inc
              }
          }
          $includes = $includes | Sort-Object -Unique
          $cppcheckIncludes = $includes -join " "
          Write-Output "Cppcheck will use: $cppcheckIncludes"
          cppcheck --enable=all --inconclusive --xml --xml-version=2 --std=c99 $cppcheckIncludes src/ include/ 2> cppcheck-results.xml

      - name: Download cppcheck-htmlreport
        run: |
          curl -L -o cppcheck-htmlreport https://raw.githubusercontent.com/danmar/cppcheck/main/htmlreport/cppcheck-htmlreport
          curl -L -o cppcheck-main.zip https://github.com/danmar/cppcheck/archive/refs/heads/main.zip
          Expand-Archive -Path cppcheck-main.zip -DestinationPath .

      - name: Generate HTML report
        run: |
          python "C:\Program Files\Cppcheck\tools\cppcheck-htmlreport" `
            --file=cppcheck-results.xml `
            --report-dir=cppcheck-html `
            --source-dir=.

      - name: Upload HTML cppcheck report
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-html-report
          path: cppcheck-html
