name: Static Analysis

on: [push, pull_request]

jobs:
  static-analysis:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (clang-tidy & cppcheck)
        run: |
          choco install -y llvm cppcheck

      - name: Add LLVM to PATH
        run: |
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure CMake
        run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: clang-tidy src/*.c -p build || exit 0

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --std=c99 src/ include/
