name: Static Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  

jobs:
  static-analysis:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (clang-tidy & cppcheck)
        run: |
          choco install -y llvm cppcheck

      - name: Add LLVM and cppcheck to PATH
        run: |
          echo "C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Find cppcheck
        run: |
          if (!(Get-Command cppcheck.exe -ErrorAction SilentlyContinue)) {
            Write-Host "cppcheck not in PATH, searching..."
            $cppcheckPath = Get-ChildItem -Path 'C:\ProgramData\chocolatey\' -Filter cppcheck.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
            if ($cppcheckPath) {
              Write-Host "Found cppcheck at $cppcheckPath"
              echo "$(Split-Path $cppcheckPath)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            } else {
              Write-Error "cppcheck.exe not found!"
              exit 1
            }
            $cppcheckPath = Get-ChildItem -Path 'C:\Program Files\' -Filter cppcheck.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
            if ($cppcheckPath) {
              Write-Host "Found cppcheck at $cppcheckPath"
              echo "$(Split-Path $cppcheckPath)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            } else {
              Write-Error "cppcheck.exe not found!"
              exit 1
            }
            $cppcheckPath = Get-ChildItem -Path 'C:\Program Files (x86)\' -Filter cppcheck.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
            if ($cppcheckPath) {
              Write-Host "Found cppcheck at $cppcheckPath"
              echo "$(Split-Path $cppcheckPath)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            } else {
              Write-Error "cppcheck.exe not found!"
              exit 1
            }
          }

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: clang-tidy src/*.c -p build || exit 0

      # - name: Run cppcheck
      #   run: cppcheck --enable=all --inconclusive --std=c99 src/ include/
